version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "step-functions-workshop"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uagj6x48hs4i"
s3_prefix = "step-functions-workshop"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
